sudo: required
services:
        - docker

before_install:
        - docker build -t ayushkumar047/docker-react -f Dockerfile.dev .

script:
        - docker run ayushkumar047/docker-react npm run test -- --coverage
